#Configuation for robot odometry EKF
#
frequency: 100

odom0: DT7/gradientOdom
#odom0: DT0/gradientOdom
#odom0: ground_truth/state
odom0_config: [true, true, true,
               false, false, false,
               false, false, false,
               false, false, false,
               false, false, false]
odom0_differential: false

imu0: imu/data
imu0_config: [false, false, false,
              false, false, false,
              false, false, false,
              false, false, false,
              false, false, false]
imu0_differential: false

odom_frame: /odom
base_link_frame: /base_link
world_frame: /odom

# initial state
initial_state: [0.0, 0.0, 0.0
                0.0, 0.0, 0.0,
                0.0, 0.0, 0.0,
                0.0, 0.0, 0.0,
                0.0, 0.0, 0.0]

# tf publish
tf: true
