#Configuation for robot odometry EKF
#
frequency: 50

odom0: DT7/gradientOdom
odom0_config: [true, true, true,
               false, false, false,
               false, false, false,
               false, false, false,
               false, false, false]
odom0_differential: false

imu0: imu/data
imu0_config: [false, false, false,
              false, false, false,
              false, false, false,
              false, false, false,
              false, false, false]
imu0_differential: false

odom_frame: /robi/odom
base_link_frame: /robi/base_link
world_frame: /robi/odom

# initial state
initial_state: [5.0, 5.0, 5.0
                0.0, 0.0, 0.0,
                0.0, 0.0, 0.0,
                0.0, 0.0, 0.0,
                0.0, 0.0, 0.0]

# tf publish
tf: true
