// Generated by gencpp from file gtec_msgs/RadarCube.msg
// DO NOT EDIT!


#ifndef GTEC_MSGS_MESSAGE_RADARCUBE_H
#define GTEC_MSGS_MESSAGE_RADARCUBE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gtec_msgs
{
template <class ContainerAllocator>
struct RadarCube_
{
  typedef RadarCube_<ContainerAllocator> Type;

  RadarCube_()
    : header()
    , fftSize(0)
    , angleBins(0)
    , data()  {
    }
  RadarCube_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , fftSize(0)
    , angleBins(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _fftSize_type;
  _fftSize_type fftSize;

   typedef int16_t _angleBins_type;
  _angleBins_type angleBins;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::gtec_msgs::RadarCube_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gtec_msgs::RadarCube_<ContainerAllocator> const> ConstPtr;

}; // struct RadarCube_

typedef ::gtec_msgs::RadarCube_<std::allocator<void> > RadarCube;

typedef boost::shared_ptr< ::gtec_msgs::RadarCube > RadarCubePtr;
typedef boost::shared_ptr< ::gtec_msgs::RadarCube const> RadarCubeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gtec_msgs::RadarCube_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gtec_msgs::RadarCube_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gtec_msgs::RadarCube_<ContainerAllocator1> & lhs, const ::gtec_msgs::RadarCube_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.fftSize == rhs.fftSize &&
    lhs.angleBins == rhs.angleBins &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gtec_msgs::RadarCube_<ContainerAllocator1> & lhs, const ::gtec_msgs::RadarCube_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gtec_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gtec_msgs::RadarCube_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gtec_msgs::RadarCube_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gtec_msgs::RadarCube_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gtec_msgs::RadarCube_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gtec_msgs::RadarCube_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gtec_msgs::RadarCube_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gtec_msgs::RadarCube_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc958423e7f6a6996cbc895eb0a5e0b2";
  }

  static const char* value(const ::gtec_msgs::RadarCube_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc958423e7f6a699ULL;
  static const uint64_t static_value2 = 0x6cbc895eb0a5e0b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::gtec_msgs::RadarCube_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gtec_msgs/RadarCube";
  }

  static const char* value(const ::gtec_msgs::RadarCube_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gtec_msgs::RadarCube_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int16 fftSize\n"
"int16 angleBins\n"
"float64[] data\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::gtec_msgs::RadarCube_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gtec_msgs::RadarCube_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.fftSize);
      stream.next(m.angleBins);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarCube_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gtec_msgs::RadarCube_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gtec_msgs::RadarCube_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "fftSize: ";
    Printer<int16_t>::stream(s, indent + "  ", v.fftSize);
    s << indent << "angleBins: ";
    Printer<int16_t>::stream(s, indent + "  ", v.angleBins);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GTEC_MSGS_MESSAGE_RADARCUBE_H
