// Generated by gencpp from file gtec_msgs/ESP32S2FTMFrame.msg
// DO NOT EDIT!


#ifndef GTEC_MSGS_MESSAGE_ESP32S2FTMFRAME_H
#define GTEC_MSGS_MESSAGE_ESP32S2FTMFRAME_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gtec_msgs
{
template <class ContainerAllocator>
struct ESP32S2FTMFrame_
{
  typedef ESP32S2FTMFrame_<ContainerAllocator> Type;

  ESP32S2FTMFrame_()
    : rssi(0)
    , rtt(0)
    , t1(0)
    , t2(0)
    , t3(0)
    , t4(0)  {
    }
  ESP32S2FTMFrame_(const ContainerAllocator& _alloc)
    : rssi(0)
    , rtt(0)
    , t1(0)
    , t2(0)
    , t3(0)
    , t4(0)  {
  (void)_alloc;
    }



   typedef int32_t _rssi_type;
  _rssi_type rssi;

   typedef int32_t _rtt_type;
  _rtt_type rtt;

   typedef int64_t _t1_type;
  _t1_type t1;

   typedef int64_t _t2_type;
  _t2_type t2;

   typedef int64_t _t3_type;
  _t3_type t3;

   typedef int64_t _t4_type;
  _t4_type t4;





  typedef boost::shared_ptr< ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator> const> ConstPtr;

}; // struct ESP32S2FTMFrame_

typedef ::gtec_msgs::ESP32S2FTMFrame_<std::allocator<void> > ESP32S2FTMFrame;

typedef boost::shared_ptr< ::gtec_msgs::ESP32S2FTMFrame > ESP32S2FTMFramePtr;
typedef boost::shared_ptr< ::gtec_msgs::ESP32S2FTMFrame const> ESP32S2FTMFrameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator1> & lhs, const ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator2> & rhs)
{
  return lhs.rssi == rhs.rssi &&
    lhs.rtt == rhs.rtt &&
    lhs.t1 == rhs.t1 &&
    lhs.t2 == rhs.t2 &&
    lhs.t3 == rhs.t3 &&
    lhs.t4 == rhs.t4;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator1> & lhs, const ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gtec_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1b894ddb8209b3399fd6809e514d068";
  }

  static const char* value(const ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa1b894ddb8209b33ULL;
  static const uint64_t static_value2 = 0x99fd6809e514d068ULL;
};

template<class ContainerAllocator>
struct DataType< ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gtec_msgs/ESP32S2FTMFrame";
  }

  static const char* value(const ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 rssi\n"
"int32 rtt\n"
"int64 t1\n"
"int64 t2\n"
"int64 t3\n"
"int64 t4\n"
;
  }

  static const char* value(const ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rssi);
      stream.next(m.rtt);
      stream.next(m.t1);
      stream.next(m.t2);
      stream.next(m.t3);
      stream.next(m.t4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ESP32S2FTMFrame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gtec_msgs::ESP32S2FTMFrame_<ContainerAllocator>& v)
  {
    s << indent << "rssi: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rssi);
    s << indent << "rtt: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rtt);
    s << indent << "t1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.t1);
    s << indent << "t2: ";
    Printer<int64_t>::stream(s, indent + "  ", v.t2);
    s << indent << "t3: ";
    Printer<int64_t>::stream(s, indent + "  ", v.t3);
    s << indent << "t4: ";
    Printer<int64_t>::stream(s, indent + "  ", v.t4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GTEC_MSGS_MESSAGE_ESP32S2FTMFRAME_H
