// Generated by gencpp from file gtec_msgs/GenericRanging.msg
// DO NOT EDIT!


#ifndef GTEC_MSGS_MESSAGE_GENERICRANGING_H
#define GTEC_MSGS_MESSAGE_GENERICRANGING_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gtec_msgs
{
template <class ContainerAllocator>
struct GenericRanging_
{
  typedef GenericRanging_<ContainerAllocator> Type;

  GenericRanging_()
    : anchorId(0)
    , tagId(0)
    , range(0)
    , seq(0)
    , rxPower(0.0)  {
    }
  GenericRanging_(const ContainerAllocator& _alloc)
    : anchorId(0)
    , tagId(0)
    , range(0)
    , seq(0)
    , rxPower(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _anchorId_type;
  _anchorId_type anchorId;

   typedef int16_t _tagId_type;
  _tagId_type tagId;

   typedef int32_t _range_type;
  _range_type range;

   typedef int32_t _seq_type;
  _seq_type seq;

   typedef double _rxPower_type;
  _rxPower_type rxPower;





  typedef boost::shared_ptr< ::gtec_msgs::GenericRanging_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gtec_msgs::GenericRanging_<ContainerAllocator> const> ConstPtr;

}; // struct GenericRanging_

typedef ::gtec_msgs::GenericRanging_<std::allocator<void> > GenericRanging;

typedef boost::shared_ptr< ::gtec_msgs::GenericRanging > GenericRangingPtr;
typedef boost::shared_ptr< ::gtec_msgs::GenericRanging const> GenericRangingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gtec_msgs::GenericRanging_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gtec_msgs::GenericRanging_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gtec_msgs::GenericRanging_<ContainerAllocator1> & lhs, const ::gtec_msgs::GenericRanging_<ContainerAllocator2> & rhs)
{
  return lhs.anchorId == rhs.anchorId &&
    lhs.tagId == rhs.tagId &&
    lhs.range == rhs.range &&
    lhs.seq == rhs.seq &&
    lhs.rxPower == rhs.rxPower;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gtec_msgs::GenericRanging_<ContainerAllocator1> & lhs, const ::gtec_msgs::GenericRanging_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gtec_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gtec_msgs::GenericRanging_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gtec_msgs::GenericRanging_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gtec_msgs::GenericRanging_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gtec_msgs::GenericRanging_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gtec_msgs::GenericRanging_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gtec_msgs::GenericRanging_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gtec_msgs::GenericRanging_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb14e8b4057fd81e694cb16617eec599";
  }

  static const char* value(const ::gtec_msgs::GenericRanging_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbb14e8b4057fd81eULL;
  static const uint64_t static_value2 = 0x694cb16617eec599ULL;
};

template<class ContainerAllocator>
struct DataType< ::gtec_msgs::GenericRanging_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gtec_msgs/GenericRanging";
  }

  static const char* value(const ::gtec_msgs::GenericRanging_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gtec_msgs::GenericRanging_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 anchorId\n"
"int16 tagId\n"
"int32 range\n"
"int32 seq\n"
"float64 rxPower\n"
;
  }

  static const char* value(const ::gtec_msgs::GenericRanging_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gtec_msgs::GenericRanging_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.anchorId);
      stream.next(m.tagId);
      stream.next(m.range);
      stream.next(m.seq);
      stream.next(m.rxPower);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenericRanging_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gtec_msgs::GenericRanging_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gtec_msgs::GenericRanging_<ContainerAllocator>& v)
  {
    s << indent << "anchorId: ";
    Printer<int16_t>::stream(s, indent + "  ", v.anchorId);
    s << indent << "tagId: ";
    Printer<int16_t>::stream(s, indent + "  ", v.tagId);
    s << indent << "range: ";
    Printer<int32_t>::stream(s, indent + "  ", v.range);
    s << indent << "seq: ";
    Printer<int32_t>::stream(s, indent + "  ", v.seq);
    s << indent << "rxPower: ";
    Printer<double>::stream(s, indent + "  ", v.rxPower);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GTEC_MSGS_MESSAGE_GENERICRANGING_H
