// Generated by gencpp from file gtec_msgs/RangingDiff.msg
// DO NOT EDIT!


#ifndef GTEC_MSGS_MESSAGE_RANGINGDIFF_H
#define GTEC_MSGS_MESSAGE_RANGINGDIFF_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gtec_msgs
{
template <class ContainerAllocator>
struct RangingDiff_
{
  typedef RangingDiff_<ContainerAllocator> Type;

  RangingDiff_()
    : anchorId(0)
    , tagId(0)
    , range(0.0)
    , distance(0.0)
    , diff(0.0)  {
    }
  RangingDiff_(const ContainerAllocator& _alloc)
    : anchorId(0)
    , tagId(0)
    , range(0.0)
    , distance(0.0)
    , diff(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _anchorId_type;
  _anchorId_type anchorId;

   typedef int16_t _tagId_type;
  _tagId_type tagId;

   typedef float _range_type;
  _range_type range;

   typedef float _distance_type;
  _distance_type distance;

   typedef float _diff_type;
  _diff_type diff;





  typedef boost::shared_ptr< ::gtec_msgs::RangingDiff_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gtec_msgs::RangingDiff_<ContainerAllocator> const> ConstPtr;

}; // struct RangingDiff_

typedef ::gtec_msgs::RangingDiff_<std::allocator<void> > RangingDiff;

typedef boost::shared_ptr< ::gtec_msgs::RangingDiff > RangingDiffPtr;
typedef boost::shared_ptr< ::gtec_msgs::RangingDiff const> RangingDiffConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gtec_msgs::RangingDiff_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gtec_msgs::RangingDiff_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gtec_msgs::RangingDiff_<ContainerAllocator1> & lhs, const ::gtec_msgs::RangingDiff_<ContainerAllocator2> & rhs)
{
  return lhs.anchorId == rhs.anchorId &&
    lhs.tagId == rhs.tagId &&
    lhs.range == rhs.range &&
    lhs.distance == rhs.distance &&
    lhs.diff == rhs.diff;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gtec_msgs::RangingDiff_<ContainerAllocator1> & lhs, const ::gtec_msgs::RangingDiff_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gtec_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::gtec_msgs::RangingDiff_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gtec_msgs::RangingDiff_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gtec_msgs::RangingDiff_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gtec_msgs::RangingDiff_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gtec_msgs::RangingDiff_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gtec_msgs::RangingDiff_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gtec_msgs::RangingDiff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6a42b09b24a1d184442ec374c7c1cbf";
  }

  static const char* value(const ::gtec_msgs::RangingDiff_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6a42b09b24a1d18ULL;
  static const uint64_t static_value2 = 0x4442ec374c7c1cbfULL;
};

template<class ContainerAllocator>
struct DataType< ::gtec_msgs::RangingDiff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gtec_msgs/RangingDiff";
  }

  static const char* value(const ::gtec_msgs::RangingDiff_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gtec_msgs::RangingDiff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 anchorId\n"
"int16 tagId\n"
"float32 range\n"
"float32 distance\n"
"float32 diff\n"
;
  }

  static const char* value(const ::gtec_msgs::RangingDiff_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gtec_msgs::RangingDiff_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.anchorId);
      stream.next(m.tagId);
      stream.next(m.range);
      stream.next(m.distance);
      stream.next(m.diff);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RangingDiff_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gtec_msgs::RangingDiff_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gtec_msgs::RangingDiff_<ContainerAllocator>& v)
  {
    s << indent << "anchorId: ";
    Printer<int16_t>::stream(s, indent + "  ", v.anchorId);
    s << indent << "tagId: ";
    Printer<int16_t>::stream(s, indent + "  ", v.tagId);
    s << indent << "range: ";
    Printer<float>::stream(s, indent + "  ", v.range);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "diff: ";
    Printer<float>::stream(s, indent + "  ", v.diff);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GTEC_MSGS_MESSAGE_RANGINGDIFF_H
