# Jackal deployment and development environment containers specification.
#
# Federico Oliva <lvofrc95@outlook.it>
#
# April 3, 2023

version: "3.9"

services:
  # Jackal base setup - melodic
  jackal-melodic-base:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.melodic.x86.base
    image: dockoly/jackal:melodic-base

  # Default Development target
  jackal-melodic-dev:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.melodic.x86.dev
      args:
        TARGET: dev
    image: dockoly/jackal:melodic-dev
    network_mode: "host"
    environment:
      TERM: xterm-256color
      DISPLAY:
      SHELL: /usr/bin/zsh
      BOARD: $USER
    privileged: true
    cap_add:
      - SYS_PTRACE
    user: ros
    stdin_open: false
    tty: true
    working_dir: /home/ros/workspace
    command:
      [
        "/bin/bash",
        "-c",
        "trap 'exit 0' TERM; sleep infinity & wait"
      ]
    volumes:
      - /dev:/dev
      - /sys:/sys
      - ~/.Xauthority:/home/ros/.Xauthority:rw
      - ~/.ssh:/home/ros/.ssh
      - ./config/.aliases.sh:/home/ros/.aliases.sh:rw
      - ./config/.p10k.zsh:/home/ros/.p10k.zsh:rw
      - ./config/.ros2_cmds.sh:/home/ros/.ros2_cmds.sh:rw
      - ./config/.zshrc:/home/ros/.zshrc:rw
      - ./config/zsh_history:/home/ros/zsh_history
      - ./config/.bashrc:/home/ros/.bashrc:rw
      - ./config/.stanis_aliases.sh:/home/ros/.stanis_aliases.sh:rw
      - ./config/defaults-dev.yaml:/home/ros/.colcon/defaults.yaml:rw
      - /etc/localtime:/etc/localtime:ro
      - ./config/gazebo:/home/ros/.gazebo
      - type: bind
        source: ../
        target: /home/ros/workspace

  # Default Development target
  jackal-melodic-dev-nvidia:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.melodic.x86.dev
      args:
        TARGET: nvidia
    image: dockoly/jackal:melodic-dev-nvidia
    runtime: nvidia
    environment:
      TERM: xterm-256color
      DISPLAY:
      SHELL: /usr/bin/zsh
      BOARD: $USER
    privileged: true
    cap_add:
      - SYS_PTRACE
    user: ros
    stdin_open: false
    tty: true
    working_dir: /home/ros/workspace
    command:
      [
        "/bin/bash",
        "-c",
        "trap 'exit 0' TERM; sleep infinity & wait"
      ]
    network_mode: host
    volumes:
      - /dev:/dev
      - /sys:/sys
      - ~/.Xauthority:/home/ros/.Xauthority:rw
      - ~/.ssh:/home/ros/.ssh
      - ./config/.aliases.sh:/home/ros/.aliases.sh:rw
      - ./config/.p10k.zsh:/home/ros/.p10k.zsh:rw
      - ./config/.ros2_cmds.sh:/home/ros/.ros2_cmds.sh:rw
      - ./config/.zshrc:/home/ros/.zshrc:rw
      - ./config/zsh_history:/home/ros/zsh_history
      - ./config/.bashrc:/home/ros/.bashrc:rw
      - ./config/.stanis_aliases.sh:/home/ros/.stanis_aliases.sh:rw
      - ./config/defaults-dev.yaml:/home/ros/.colcon/defaults.yaml:rw
      - /etc/localtime:/etc/localtime:ro
      - ./config/gazebo:/home/ros/.gazebo
      - type: bind
        source: ../
        target: /home/ros/workspace

  # Default Development target
  matlab-base:
    build:
      context: .
      network: host
      dockerfile: Dockerfile.matlab.x86.2023.base
      args:
        TARGET: nvidia
    image: dockoly/jackal:matlab-base
    runtime: nvidia
    environment:
      TERM: xterm-256color
      DISPLAY:
      SHELL: /bin/bash
      BOARD: $USER
    privileged: true
    cap_add:
      - SYS_PTRACE
    user: ros
    stdin_open: false
    tty: true
    working_dir: /home/ros/workspace
    command:
      [
        "/bin/bash",
        "-c",
        "trap 'exit 0' TERM; sleep infinity & wait"
      ]
    network_mode: host
    volumes:
      - /dev:/dev
      - /sys:/sys
      - ~/.Xauthority:/home/ros/.Xauthority:rw
      - ~/.ssh:/home/ros/.ssh
      - ./config/.aliases.sh:/home/ros/.aliases.sh:rw
      - ./config/.p10k.zsh:/home/ros/.p10k.zsh:rw
      - ./config/.ros2_cmds.sh:/home/ros/.ros2_cmds.sh:rw
      - ./config/.zshrc:/home/ros/.zshrc:rw
      - ./config/zsh_history:/home/ros/zsh_history
      - ./config/.bashrc:/home/ros/.bashrc:rw
      - ./config/.stanis_aliases.sh:/home/ros/.stanis_aliases.sh:rw
      - ./config/defaults-dev.yaml:/home/ros/.colcon/defaults.yaml:rw
      - /etc/localtime:/etc/localtime:ro
      - ./config/gazebo:/home/ros/.gazebo
      - type: bind
        source: ../
        target: /home/ros/workspace

networks:
  customnetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/16
