// Generated by gencpp from file jackal_op/MeshUWBCentral.msg
// DO NOT EDIT!


#ifndef JACKAL_OP_MESSAGE_MESHUWBCENTRAL_H
#define JACKAL_OP_MESSAGE_MESHUWBCENTRAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace jackal_op
{
template <class ContainerAllocator>
struct MeshUWBCentral_
{
  typedef MeshUWBCentral_<ContainerAllocator> Type;

  MeshUWBCentral_()
    : header()
    , DC()  {
    }
  MeshUWBCentral_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , DC(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _DC_type;
  _DC_type DC;





  typedef boost::shared_ptr< ::jackal_op::MeshUWBCentral_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jackal_op::MeshUWBCentral_<ContainerAllocator> const> ConstPtr;

}; // struct MeshUWBCentral_

typedef ::jackal_op::MeshUWBCentral_<std::allocator<void> > MeshUWBCentral;

typedef boost::shared_ptr< ::jackal_op::MeshUWBCentral > MeshUWBCentralPtr;
typedef boost::shared_ptr< ::jackal_op::MeshUWBCentral const> MeshUWBCentralConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jackal_op::MeshUWBCentral_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jackal_op::MeshUWBCentral_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jackal_op::MeshUWBCentral_<ContainerAllocator1> & lhs, const ::jackal_op::MeshUWBCentral_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.DC == rhs.DC;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jackal_op::MeshUWBCentral_<ContainerAllocator1> & lhs, const ::jackal_op::MeshUWBCentral_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jackal_op

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::jackal_op::MeshUWBCentral_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jackal_op::MeshUWBCentral_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jackal_op::MeshUWBCentral_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jackal_op::MeshUWBCentral_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jackal_op::MeshUWBCentral_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jackal_op::MeshUWBCentral_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jackal_op::MeshUWBCentral_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5bbc7e1874ce4e720dbb04b3a0e1e74b";
  }

  static const char* value(const ::jackal_op::MeshUWBCentral_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5bbc7e1874ce4e72ULL;
  static const uint64_t static_value2 = 0x0dbb04b3a0e1e74bULL;
};

template<class ContainerAllocator>
struct DataType< ::jackal_op::MeshUWBCentral_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jackal_op/MeshUWBCentral";
  }

  static const char* value(const ::jackal_op::MeshUWBCentral_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jackal_op::MeshUWBCentral_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64[] DC\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::jackal_op::MeshUWBCentral_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jackal_op::MeshUWBCentral_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.DC);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MeshUWBCentral_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jackal_op::MeshUWBCentral_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jackal_op::MeshUWBCentral_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "DC[]" << std::endl;
    for (size_t i = 0; i < v.DC.size(); ++i)
    {
      s << indent << "  DC[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.DC[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // JACKAL_OP_MESSAGE_MESHUWBCENTRAL_H
