#Configuation for robot odometry EKF
#
jack_hybobs_subIMU: "/robi/imu/data"
jack_hybobs_subOdom: "/robi/DT0/gradientOdom"
jack_hybobs_pubOdom: "/HybObs/Odom"
jack_hybobs_pubIMU: "/HybObs/IMU"
jack_hybobs_pubBias: "/HybObs/Bias"
DistjackAPIName: "HybObsAPI"
NanchorMesh: 4
HYBrate: 100