#Configuation for robot odometry EKF
#
jack_disthandle_subT: "/gtec/toa/ranging"
jack_disthandle_subA: "/gtec/toa/anchors"
jack_disthandle_pubDist: "/DT0/DT"
jack_disthandle_pubGrad: "/DT0/gradient"
jackAPIName: "DT0API"
jack_disthandle_tagID: 0
NanchorMesh: 4
Ntags: 3
TagPair: -1
TagDists: [0.0]
GradientFlag: 0
UWBrate: 5