#Configuation for robot odometry EKF
#
jack_hybobs_subIMU: "/imu/data"
jack_hybobs_subOdom: "/DT2/gradientOdom"
jack_hybobs_pubOdom: "/HYB2/Odom"
jack_hybobs_pubIMU: "/HYB2/IMU"
jack_hybobs_pubBias: "/HYB2/Bias"
DistjackAPIName: "HYB2API"
NanchorMesh: 4
HYBrate: 100