#Configuation for robot odometry EKF
#
jack_disttrue_subA: "/gtec/toa/anchors"
jack_disttrue_subOdom: "/ground_truth/state"
jack_disttrue_pubDist: "/gtec/toa/ranging"
jack_disttrue_pubAnchors: "/gtec/toa/anchors"
DistjackAPIName: "MeshTrueAPI"
NanchorMesh: 4
Ntags: 1
TagDists: [0.0]
UWBrate: 5