#Configuation for robot odometry EKF
#
jack_disthandle_subT: "/MeshTrue/DTrue"
jack_disthandle_subA: "/gtec/toa/anchors"
jack_disthandle_pubDist: "/robi/DT0/DT"
jack_disthandle_pubGrad: "/robi/DT0/gradient"
jackAPIName: "DT0API"
jack_disthandle_tagID: 0
NanchorMesh: 4
GradientFlag: 0
UWBrate: 5