#Configuation for robot odometry EKF
#
jack_hybobs_subIMU: "/imu/data"
jack_hybobs_subOdom: "/DT1/gradientOdom"
jack_hybobs_pubOdom: "/HYB1/Odom"
jack_hybobs_pubIMU: "/HYB1/IMU"
jack_hybobs_pubBias: "/HYB1/Bias"
DistjackAPIName: "HYB1API"
NanchorMesh: 4
HYBrate: 100