(cl:in-package gtec_msgs-msg)
(cl:export '(ORIGINID-VAL
          ORIGINID
          ORIGINTYPE-VAL
          ORIGINTYPE
          DESTINATIONID-VAL
          DESTINATIONID
          DESTINATIONTYPE-VAL
          DESTINATIONTYPE
          RANGE-VAL
          RANGE
          TS-VAL
          TS
          SEQ-VAL
          SEQ
          RXPOWER-VAL
          RXPOWER
          CHANNEL-VAL
          CHANNEL
          DATARATE-VAL
          DATARATE
          PRF-VAL
          PRF
          PREAMBLELENGTH-VAL
          PREAMBLELENGTH
          TXGAIN-VAL
          TXGAIN
          ANGLE-VAL
          ANGLE
          CIR-VAL
          CIR
))