(cl:in-package gtec_msgs-msg)
(cl:export '(ANCHORID-VAL
          ANCHORID
          TAGID-VAL
          TAGID
          RANGE-VAL
          RANGE
          RAWRANGE-VAL
          RAWRANGE
          SEQ-VAL
          SEQ
          MAXNOISE-VAL
          MAXNOISE
          STDNOISE-VAL
          STDNOISE
          FIRSTPATHAMP1-VAL
          FIRSTPATHAMP1
          FIRSTPATHAMP2-VAL
          FIRSTPATHAMP2
          FIRSTPATHAMP3-VAL
          FIRSTPATHAMP3
          MAXGROWTHCIR-VAL
          MAXGROWTHCIR
          RXPREAMCOUNT-VAL
          RXPREAMCOUNT
          FIRSTPATH-VAL
          FIRSTPATH
          CHANNEL-VAL
          CHANNEL
          PRF-VAL
          PRF
          DATARATE-VAL
          DATARATE
          PREAMBLELENGTH-VAL
          PREAMBLELENGTH
          PACSIZE-VAL
          PACSIZE
))