# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from gtec_msgs/ESP32S2FTMFrame.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ESP32S2FTMFrame(genpy.Message):
  _md5sum = "a1b894ddb8209b3399fd6809e514d068"
  _type = "gtec_msgs/ESP32S2FTMFrame"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 rssi
int32 rtt
int64 t1
int64 t2
int64 t3
int64 t4"""
  __slots__ = ['rssi','rtt','t1','t2','t3','t4']
  _slot_types = ['int32','int32','int64','int64','int64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       rssi,rtt,t1,t2,t3,t4

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ESP32S2FTMFrame, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.rssi is None:
        self.rssi = 0
      if self.rtt is None:
        self.rtt = 0
      if self.t1 is None:
        self.t1 = 0
      if self.t2 is None:
        self.t2 = 0
      if self.t3 is None:
        self.t3 = 0
      if self.t4 is None:
        self.t4 = 0
    else:
      self.rssi = 0
      self.rtt = 0
      self.t1 = 0
      self.t2 = 0
      self.t3 = 0
      self.t4 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2i4q().pack(_x.rssi, _x.rtt, _x.t1, _x.t2, _x.t3, _x.t4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.rssi, _x.rtt, _x.t1, _x.t2, _x.t3, _x.t4,) = _get_struct_2i4q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2i4q().pack(_x.rssi, _x.rtt, _x.t1, _x.t2, _x.t3, _x.t4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.rssi, _x.rtt, _x.t1, _x.t2, _x.t3, _x.t4,) = _get_struct_2i4q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i4q = None
def _get_struct_2i4q():
    global _struct_2i4q
    if _struct_2i4q is None:
        _struct_2i4q = struct.Struct("<2i4q")
    return _struct_2i4q
