# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from gtec_msgs/GenericRanging.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GenericRanging(genpy.Message):
  _md5sum = "bb14e8b4057fd81e694cb16617eec599"
  _type = "gtec_msgs/GenericRanging"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 anchorId
int16 tagId
int32 range
int32 seq
float64 rxPower"""
  __slots__ = ['anchorId','tagId','range','seq','rxPower']
  _slot_types = ['int16','int16','int32','int32','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       anchorId,tagId,range,seq,rxPower

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GenericRanging, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.anchorId is None:
        self.anchorId = 0
      if self.tagId is None:
        self.tagId = 0
      if self.range is None:
        self.range = 0
      if self.seq is None:
        self.seq = 0
      if self.rxPower is None:
        self.rxPower = 0.
    else:
      self.anchorId = 0
      self.tagId = 0
      self.range = 0
      self.seq = 0
      self.rxPower = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2h2id().pack(_x.anchorId, _x.tagId, _x.range, _x.seq, _x.rxPower))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.anchorId, _x.tagId, _x.range, _x.seq, _x.rxPower,) = _get_struct_2h2id().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2h2id().pack(_x.anchorId, _x.tagId, _x.range, _x.seq, _x.rxPower))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.anchorId, _x.tagId, _x.range, _x.seq, _x.rxPower,) = _get_struct_2h2id().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2h2id = None
def _get_struct_2h2id():
    global _struct_2h2id
    if _struct_2h2id is None:
        _struct_2h2id = struct.Struct("<2h2id")
    return _struct_2h2id
