// Generated by gencpp from file robot_localization_custom/FromLL.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCALIZATION_CUSTOM_MESSAGE_FROMLL_H
#define ROBOT_LOCALIZATION_CUSTOM_MESSAGE_FROMLL_H

#include <ros/service_traits.h>


#include <robot_localization_custom/FromLLRequest.h>
#include <robot_localization_custom/FromLLResponse.h>


namespace robot_localization_custom
{

struct FromLL
{

typedef FromLLRequest Request;
typedef FromLLResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FromLL
} // namespace robot_localization_custom


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_localization_custom::FromLL > {
  static const char* value()
  {
    return "a6cd7064e35acbe3e4c3ac3dc5fd8265";
  }

  static const char* value(const ::robot_localization_custom::FromLL&) { return value(); }
};

template<>
struct DataType< ::robot_localization_custom::FromLL > {
  static const char* value()
  {
    return "robot_localization_custom/FromLL";
  }

  static const char* value(const ::robot_localization_custom::FromLL&) { return value(); }
};


// service_traits::MD5Sum< ::robot_localization_custom::FromLLRequest> should match
// service_traits::MD5Sum< ::robot_localization_custom::FromLL >
template<>
struct MD5Sum< ::robot_localization_custom::FromLLRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization_custom::FromLL >::value();
  }
  static const char* value(const ::robot_localization_custom::FromLLRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization_custom::FromLLRequest> should match
// service_traits::DataType< ::robot_localization_custom::FromLL >
template<>
struct DataType< ::robot_localization_custom::FromLLRequest>
{
  static const char* value()
  {
    return DataType< ::robot_localization_custom::FromLL >::value();
  }
  static const char* value(const ::robot_localization_custom::FromLLRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_localization_custom::FromLLResponse> should match
// service_traits::MD5Sum< ::robot_localization_custom::FromLL >
template<>
struct MD5Sum< ::robot_localization_custom::FromLLResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization_custom::FromLL >::value();
  }
  static const char* value(const ::robot_localization_custom::FromLLResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization_custom::FromLLResponse> should match
// service_traits::DataType< ::robot_localization_custom::FromLL >
template<>
struct DataType< ::robot_localization_custom::FromLLResponse>
{
  static const char* value()
  {
    return DataType< ::robot_localization_custom::FromLL >::value();
  }
  static const char* value(const ::robot_localization_custom::FromLLResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCALIZATION_CUSTOM_MESSAGE_FROMLL_H
