// Generated by gencpp from file robot_localization_custom/SetPose.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCALIZATION_CUSTOM_MESSAGE_SETPOSE_H
#define ROBOT_LOCALIZATION_CUSTOM_MESSAGE_SETPOSE_H

#include <ros/service_traits.h>


#include <robot_localization_custom/SetPoseRequest.h>
#include <robot_localization_custom/SetPoseResponse.h>


namespace robot_localization_custom
{

struct SetPose
{

typedef SetPoseRequest Request;
typedef SetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPose
} // namespace robot_localization_custom


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_localization_custom::SetPose > {
  static const char* value()
  {
    return "4f3e0bbe7a24e1f929488cd1970222d3";
  }

  static const char* value(const ::robot_localization_custom::SetPose&) { return value(); }
};

template<>
struct DataType< ::robot_localization_custom::SetPose > {
  static const char* value()
  {
    return "robot_localization_custom/SetPose";
  }

  static const char* value(const ::robot_localization_custom::SetPose&) { return value(); }
};


// service_traits::MD5Sum< ::robot_localization_custom::SetPoseRequest> should match
// service_traits::MD5Sum< ::robot_localization_custom::SetPose >
template<>
struct MD5Sum< ::robot_localization_custom::SetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization_custom::SetPose >::value();
  }
  static const char* value(const ::robot_localization_custom::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization_custom::SetPoseRequest> should match
// service_traits::DataType< ::robot_localization_custom::SetPose >
template<>
struct DataType< ::robot_localization_custom::SetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::robot_localization_custom::SetPose >::value();
  }
  static const char* value(const ::robot_localization_custom::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_localization_custom::SetPoseResponse> should match
// service_traits::MD5Sum< ::robot_localization_custom::SetPose >
template<>
struct MD5Sum< ::robot_localization_custom::SetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization_custom::SetPose >::value();
  }
  static const char* value(const ::robot_localization_custom::SetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization_custom::SetPoseResponse> should match
// service_traits::DataType< ::robot_localization_custom::SetPose >
template<>
struct DataType< ::robot_localization_custom::SetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::robot_localization_custom::SetPose >::value();
  }
  static const char* value(const ::robot_localization_custom::SetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCALIZATION_CUSTOM_MESSAGE_SETPOSE_H
