// Generated by gencpp from file robot_localization_custom/SetUTMZone.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCALIZATION_CUSTOM_MESSAGE_SETUTMZONE_H
#define ROBOT_LOCALIZATION_CUSTOM_MESSAGE_SETUTMZONE_H

#include <ros/service_traits.h>


#include <robot_localization_custom/SetUTMZoneRequest.h>
#include <robot_localization_custom/SetUTMZoneResponse.h>


namespace robot_localization_custom
{

struct SetUTMZone
{

typedef SetUTMZoneRequest Request;
typedef SetUTMZoneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetUTMZone
} // namespace robot_localization_custom


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_localization_custom::SetUTMZone > {
  static const char* value()
  {
    return "893fd74d45efde020666acda18d3cccc";
  }

  static const char* value(const ::robot_localization_custom::SetUTMZone&) { return value(); }
};

template<>
struct DataType< ::robot_localization_custom::SetUTMZone > {
  static const char* value()
  {
    return "robot_localization_custom/SetUTMZone";
  }

  static const char* value(const ::robot_localization_custom::SetUTMZone&) { return value(); }
};


// service_traits::MD5Sum< ::robot_localization_custom::SetUTMZoneRequest> should match
// service_traits::MD5Sum< ::robot_localization_custom::SetUTMZone >
template<>
struct MD5Sum< ::robot_localization_custom::SetUTMZoneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization_custom::SetUTMZone >::value();
  }
  static const char* value(const ::robot_localization_custom::SetUTMZoneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization_custom::SetUTMZoneRequest> should match
// service_traits::DataType< ::robot_localization_custom::SetUTMZone >
template<>
struct DataType< ::robot_localization_custom::SetUTMZoneRequest>
{
  static const char* value()
  {
    return DataType< ::robot_localization_custom::SetUTMZone >::value();
  }
  static const char* value(const ::robot_localization_custom::SetUTMZoneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_localization_custom::SetUTMZoneResponse> should match
// service_traits::MD5Sum< ::robot_localization_custom::SetUTMZone >
template<>
struct MD5Sum< ::robot_localization_custom::SetUTMZoneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization_custom::SetUTMZone >::value();
  }
  static const char* value(const ::robot_localization_custom::SetUTMZoneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization_custom::SetUTMZoneResponse> should match
// service_traits::DataType< ::robot_localization_custom::SetUTMZone >
template<>
struct DataType< ::robot_localization_custom::SetUTMZoneResponse>
{
  static const char* value()
  {
    return DataType< ::robot_localization_custom::SetUTMZone >::value();
  }
  static const char* value(const ::robot_localization_custom::SetUTMZoneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCALIZATION_CUSTOM_MESSAGE_SETUTMZONE_H
