// Generated by gencpp from file robot_localization_custom/ToggleFilterProcessing.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCALIZATION_CUSTOM_MESSAGE_TOGGLEFILTERPROCESSING_H
#define ROBOT_LOCALIZATION_CUSTOM_MESSAGE_TOGGLEFILTERPROCESSING_H

#include <ros/service_traits.h>


#include <robot_localization_custom/ToggleFilterProcessingRequest.h>
#include <robot_localization_custom/ToggleFilterProcessingResponse.h>


namespace robot_localization_custom
{

struct ToggleFilterProcessing
{

typedef ToggleFilterProcessingRequest Request;
typedef ToggleFilterProcessingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToggleFilterProcessing
} // namespace robot_localization_custom


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_localization_custom::ToggleFilterProcessing > {
  static const char* value()
  {
    return "a8e1711976dcda1b8b978eee81e85498";
  }

  static const char* value(const ::robot_localization_custom::ToggleFilterProcessing&) { return value(); }
};

template<>
struct DataType< ::robot_localization_custom::ToggleFilterProcessing > {
  static const char* value()
  {
    return "robot_localization_custom/ToggleFilterProcessing";
  }

  static const char* value(const ::robot_localization_custom::ToggleFilterProcessing&) { return value(); }
};


// service_traits::MD5Sum< ::robot_localization_custom::ToggleFilterProcessingRequest> should match
// service_traits::MD5Sum< ::robot_localization_custom::ToggleFilterProcessing >
template<>
struct MD5Sum< ::robot_localization_custom::ToggleFilterProcessingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization_custom::ToggleFilterProcessing >::value();
  }
  static const char* value(const ::robot_localization_custom::ToggleFilterProcessingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization_custom::ToggleFilterProcessingRequest> should match
// service_traits::DataType< ::robot_localization_custom::ToggleFilterProcessing >
template<>
struct DataType< ::robot_localization_custom::ToggleFilterProcessingRequest>
{
  static const char* value()
  {
    return DataType< ::robot_localization_custom::ToggleFilterProcessing >::value();
  }
  static const char* value(const ::robot_localization_custom::ToggleFilterProcessingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_localization_custom::ToggleFilterProcessingResponse> should match
// service_traits::MD5Sum< ::robot_localization_custom::ToggleFilterProcessing >
template<>
struct MD5Sum< ::robot_localization_custom::ToggleFilterProcessingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization_custom::ToggleFilterProcessing >::value();
  }
  static const char* value(const ::robot_localization_custom::ToggleFilterProcessingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization_custom::ToggleFilterProcessingResponse> should match
// service_traits::DataType< ::robot_localization_custom::ToggleFilterProcessing >
template<>
struct DataType< ::robot_localization_custom::ToggleFilterProcessingResponse>
{
  static const char* value()
  {
    return DataType< ::robot_localization_custom::ToggleFilterProcessing >::value();
  }
  static const char* value(const ::robot_localization_custom::ToggleFilterProcessingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCALIZATION_CUSTOM_MESSAGE_TOGGLEFILTERPROCESSING_H
