// Generated by gencpp from file robot_localization_custom/ToLL.msg
// DO NOT EDIT!


#ifndef ROBOT_LOCALIZATION_CUSTOM_MESSAGE_TOLL_H
#define ROBOT_LOCALIZATION_CUSTOM_MESSAGE_TOLL_H

#include <ros/service_traits.h>


#include <robot_localization_custom/ToLLRequest.h>
#include <robot_localization_custom/ToLLResponse.h>


namespace robot_localization_custom
{

struct ToLL
{

typedef ToLLRequest Request;
typedef ToLLResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToLL
} // namespace robot_localization_custom


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_localization_custom::ToLL > {
  static const char* value()
  {
    return "ad0cbea3b8423e9ccf1b2ebeefc50b92";
  }

  static const char* value(const ::robot_localization_custom::ToLL&) { return value(); }
};

template<>
struct DataType< ::robot_localization_custom::ToLL > {
  static const char* value()
  {
    return "robot_localization_custom/ToLL";
  }

  static const char* value(const ::robot_localization_custom::ToLL&) { return value(); }
};


// service_traits::MD5Sum< ::robot_localization_custom::ToLLRequest> should match
// service_traits::MD5Sum< ::robot_localization_custom::ToLL >
template<>
struct MD5Sum< ::robot_localization_custom::ToLLRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization_custom::ToLL >::value();
  }
  static const char* value(const ::robot_localization_custom::ToLLRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization_custom::ToLLRequest> should match
// service_traits::DataType< ::robot_localization_custom::ToLL >
template<>
struct DataType< ::robot_localization_custom::ToLLRequest>
{
  static const char* value()
  {
    return DataType< ::robot_localization_custom::ToLL >::value();
  }
  static const char* value(const ::robot_localization_custom::ToLLRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_localization_custom::ToLLResponse> should match
// service_traits::MD5Sum< ::robot_localization_custom::ToLL >
template<>
struct MD5Sum< ::robot_localization_custom::ToLLResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_localization_custom::ToLL >::value();
  }
  static const char* value(const ::robot_localization_custom::ToLLResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_localization_custom::ToLLResponse> should match
// service_traits::DataType< ::robot_localization_custom::ToLL >
template<>
struct DataType< ::robot_localization_custom::ToLLResponse>
{
  static const char* value()
  {
    return DataType< ::robot_localization_custom::ToLL >::value();
  }
  static const char* value(const ::robot_localization_custom::ToLLResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_LOCALIZATION_CUSTOM_MESSAGE_TOLL_H
