
classdef MeshUWBCentral < ros.Message
    %MeshUWBCentral MATLAB implementation of jackal_op/MeshUWBCentral
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'jackal_op/MeshUWBCentral' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '5bbc7e1874ce4e720dbb04b3a0e1e74b' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'DC' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'DC' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        DC
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'MeshUWBCentral', 'Header')
            obj.Header = val;
        end
        function set.DC(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'MeshUWBCentral', 'DC');
            obj.DC = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.jackal_op.MeshUWBCentral.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.jackal_op.MeshUWBCentral(strObj);
        end
    end
end
